var namespace_pavalisoft_1_1_caching_1_1_sql_server =
[
    [ "ExtendedSqlServerCache", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_extended_sql_server_cache.html", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_extended_sql_server_cache" ],
    [ "SqlServerDistributedCacheStore", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_sql_server_distributed_cache_store.html", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_sql_server_distributed_cache_store" ],
    [ "SqlServerDistributedCacheStoreType", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_sql_server_distributed_cache_store_type.html", "class_pavalisoft_1_1_caching_1_1_sql_server_1_1_sql_server_distributed_cache_store_type" ]
];